import { makeNameFactory } from './names.js';

/** Game phases. */
export const PHASE = Object.freeze({
  LOBBY: 'lobby',
  COUNTDOWN: 'countdown',
  RUNNING: 'running',
  ENDED: 'ended',
});

export const DEFAULTS = Object.freeze({
  countdownMs: 3000,
  durationMs: 30000,
  maxTapsPerBatch: 100, // anti-accident bound (retry storms, buggy client loops), NOT anti-cheat
  topN: 10,
});

/**
 * In-memory authoritative game state. Pure with respect to time: every method
 * that depends on "now" takes it as an argument, so behavior is fully
 * deterministic and unit-testable. The HTTP layer (server.js) is the only thing
 * that reads the real clock.
 */
export class Game {
  /**
   * @param {object} [opts]
   * @param {number} [opts.countdownMs]
   * @param {number} [opts.durationMs] default round length (overridable per start)
   * @param {number} [opts.maxTapsPerBatch]
   * @param {number} [opts.topN]
   * @param {() => {name,emoji,seq,label}} [opts.nameFactory] injectable for tests
   * @param {(result: object) => void} [opts.onEnded] called once when a round ends
   */
  constructor(opts = {}) {
    this.countdownMs = opts.countdownMs ?? DEFAULTS.countdownMs;
    this.defaultDurationMs = opts.durationMs ?? DEFAULTS.durationMs;
    this.maxTapsPerBatch = opts.maxTapsPerBatch ?? DEFAULTS.maxTapsPerBatch;
    this.topN = opts.topN ?? DEFAULTS.topN;
    this._nextName = opts.nameFactory ?? makeNameFactory();
    this._onEnded = opts.onEnded ?? null;

    /** @type {Map<string, {id, name, emoji, seq, count}>} */
    this.players = new Map();
    /** @type {Map<string, number>} id -> 1-based rank (snapshot) */
    this.ranks = new Map();
    /** @type {Array<{rank, id, name, emoji, count}>} cached top-N */
    this.top = [];

    this.phase = PHASE.LOBBY;
    this.startsAt = null; // epoch ms the round goes live (countdown -> running)
    this.endsAt = null; // epoch ms the round ends
    this.durationMs = this.defaultDurationMs;
    this.winner = null;
    this.totalTaps = 0;
    this.roundId = 0;
  }

  /**
   * Registers a new player and returns its identity.
   * @param {string} id stable client id (uuid) generated by caller
   */
  join(id) {
    if (this.players.has(id)) return this._identity(this.players.get(id));
    const ident = this._nextName();
    const player = { id, name: ident.name, emoji: ident.emoji, seq: ident.seq, count: 0 };
    this.players.set(id, player);
    return this._identity(player);
  }

  /** Returns true if the id is a known player. */
  has(id) {
    return this.players.has(id);
  }

  /**
   * Records a batch of taps. Only counts while the round is RUNNING and before
   * endsAt. The batch is clamped to maxTapsPerBatch as accident protection.
   * @returns {object} the player's view (see playerView)
   */
  tap(id, n, now) {
    this._advance(now);
    const player = this.players.get(id);
    if (!player) return null;
    if (this.phase === PHASE.RUNNING && now < this.endsAt) {
      let count = Number(n);
      if (!Number.isFinite(count) || count <= 0) count = 0;
      count = Math.min(Math.floor(count), this.maxTapsPerBatch);
      if (count > 0) {
        player.count += count;
        this.totalTaps += count;
      }
    }
    return this.playerView(id, now);
  }

  /**
   * Starts a new round: zeroes all counts, enters COUNTDOWN, then RUNNING.
   * @param {object} [opts] { durationMs, now }
   */
  start({ durationMs, now } = {}) {
    const dur = Number.isFinite(durationMs) && durationMs > 0 ? Math.floor(durationMs) : this.defaultDurationMs;
    for (const p of this.players.values()) p.count = 0;
    this.totalTaps = 0;
    this.winner = null;
    this.durationMs = dur;
    this.startsAt = now + this.countdownMs;
    this.endsAt = this.startsAt + dur;
    this.phase = PHASE.COUNTDOWN;
    this.roundId += 1;
    this._recount();
    return this.publicState(now);
  }

  /** Resets back to LOBBY, zeroing counts but keeping joined players & names. */
  reset({ now } = {}) {
    for (const p of this.players.values()) p.count = 0;
    this.totalTaps = 0;
    this.winner = null;
    this.startsAt = null;
    this.endsAt = null;
    this.phase = PHASE.LOBBY;
    this._recount();
    return this.publicState(now ?? 0);
  }

  /**
   * Advances the phase machine and refreshes rank/top snapshots. Safe to call
   * as often as you like (e.g. every 100ms from a timer, and on every request).
   */
  tick(now) {
    this._advance(now);
    this._recount();
    return this.publicState(now);
  }

  // --- internals -----------------------------------------------------------

  _advance(now) {
    if (this.phase === PHASE.COUNTDOWN && now >= this.startsAt) {
      this.phase = PHASE.RUNNING;
    }
    if (this.phase === PHASE.RUNNING && now >= this.endsAt) {
      this.phase = PHASE.ENDED;
      this._recount();
      this.winner = this.top[0] ?? null;
      if (this._onEnded) {
        try {
          this._onEnded(this.results());
        } catch {
          /* persistence failures must never crash the game loop */
        }
      }
    }
  }

  _recount() {
    const sorted = [...this.players.values()].sort(
      (a, b) => b.count - a.count || a.seq - b.seq, // ties: earlier joiner ranks higher
    );
    const ranks = new Map();
    const top = [];
    for (let i = 0; i < sorted.length; i++) {
      const p = sorted[i];
      ranks.set(p.id, i + 1);
      if (i < this.topN) {
        top.push({ rank: i + 1, id: p.id, name: p.name, emoji: p.emoji, seq: p.seq, count: p.count });
      }
    }
    this.ranks = ranks;
    this.top = top;
  }

  _identity(p) {
    return { id: p.id, name: p.name, emoji: p.emoji, seq: p.seq, label: `${p.name} #${p.seq}` };
  }

  /** Per-player view returned to a phone after /tap or /state. */
  playerView(id, now) {
    const p = this.players.get(id);
    const base = {
      phase: this.phase,
      serverNow: now,
      startsAt: this.startsAt,
      endsAt: this.endsAt,
      countdownMs: this.countdownMs,
      durationMs: this.durationMs,
      total: this.players.size,
      roundId: this.roundId, // lets the phone reset optimistic state on a new round
    };
    if (!p) return { ...base, known: false };
    return {
      ...base,
      known: true,
      id: p.id,
      name: p.name,
      emoji: p.emoji,
      label: `${p.name} #${p.seq}`,
      yourRank: this.ranks.get(id) ?? this.players.size,
      yourCount: p.count,
    };
  }

  /** Aggregate state broadcast to the big screen via SSE. */
  publicState(now) {
    return {
      phase: this.phase,
      serverNow: now,
      startsAt: this.startsAt,
      endsAt: this.endsAt,
      countdownMs: this.countdownMs,
      durationMs: this.durationMs,
      total: this.players.size,
      totalTaps: this.totalTaps,
      top: this.top,
      winner: this.winner,
      roundId: this.roundId,
    };
  }

  /** Final results, used for persistence at round end. */
  results() {
    const sorted = [...this.players.values()]
      .sort((a, b) => b.count - a.count || a.seq - b.seq)
      .map((p, i) => ({ rank: i + 1, name: p.name, seq: p.seq, count: p.count }));
    return {
      roundId: this.roundId,
      durationMs: this.durationMs,
      endedAt: this.endsAt,
      totalPlayers: this.players.size,
      totalTaps: this.totalTaps,
      winner: sorted[0] ?? null,
      leaderboard: sorted.slice(0, 50),
    };
  }
}
